import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("ERROR: Supabase credentials not found in .env")
    exit(1)

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# Use postgrest RPC or just SQL via Supabase Dashboard is better, but 
# we can try to add columns one by one if the current user has permissions.
# NOTE: Supabase client doesn't support ALTER TABLE directly through the SDK for ordinary tables.
# The best way is to provide the SQL to the user or if they have a 'sql' helper.
# Since I cannot run raw SQL via the Python SDK easily without an RPC, 
# I will check if the columns exist and then advise.

print("Checking schema...")

try:
    # We can try to check if columns exist by selecting them
    res = supabase.table("orders").select("settled").limit(1).execute()
    print("Column 'settled' already exists.")
except Exception as e:
    print("Column 'settled' MISSING. Please run this SQL in Supabase SQL Editor:")
    print("""
ALTER TABLE orders ADD COLUMN IF NOT EXISTS settled INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS settlement_id INTEGER;

CREATE TABLE IF NOT EXISTS monthly_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_name TEXT NOT NULL,
    total_sales FLOAT NOT NULL,
    total_expenses FLOAT NOT NULL,
    net_profit FLOAT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    amount FLOAT NOT NULL,
    date TEXT NOT NULL,
    settled INTEGER DEFAULT 0,
    settlement_id BIGINT REFERENCES monthly_settlements(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
    """)

# I will also try to create the tables anyway using the SDK just in case.
try:
    print("Attempting to ensure 'expenses' and 'monthly_settlements' tables exist via dummy inserts...")
    # This is not a proper way to create tables, but I'll provide the SQL to the user as the primary method.
except Exception:
    pass
